### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by savelive** [joeshang/joycar#1]
尊敬的两位学长你们好，这个项目让我很心动！我有和你们类似的想法，想DIY一个遥控车。目前是具备一些简单的硬件知识和不错的软件知识，如果这个项目还有人维护(能和原作者沟通)，那它将是我独立把它完成的信心所在
       最后，希望学长看到能回复一下，谢谢！

**Comment by joeshang** [comment]
你好，这个项目是学生时代的项目，当时完成并且也演示了，达到项目最初的目的，至此不再维护。
如果有想法，最好的办法就是现在开始搞，希望能 Have Fun and Enjoy It。
